// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg23GVnk2GUoUmtZvQZmZnvqEkVGQRtcU',
    appId: '1:607075166212:web:f34b9d6899d4103eeb6d51',
    messagingSenderId: '607075166212',
    projectId: 'chat-application-801ff',
    authDomain: 'chat-application-801ff.firebaseapp.com',
    storageBucket: 'chat-application-801ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALfIS-MEX6HNeFKiIDkdVg7YuylnCUEyM',
    appId: '1:607075166212:android:4ed2708dde268b1aeb6d51',
    messagingSenderId: '607075166212',
    projectId: 'chat-application-801ff',
    storageBucket: 'chat-application-801ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5JfKMrT2-bFX20K_tVvD-cVRV2q6lX4',
    appId: '1:607075166212:ios:42ea61575da456edeb6d51',
    messagingSenderId: '607075166212',
    projectId: 'chat-application-801ff',
    storageBucket: 'chat-application-801ff.appspot.com',
    iosBundleId: 'com.example.messenger',
  );
}
